---
name: "Updatecli daily"

on:
  # run daily or manually
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install updatecli"
        uses: "updatecli/updatecli-action@v2.75.0"
        with:
          version: "v0.92.0"
        
      - name: "Install Releasepost"
        uses: "updatecli/releasepost-action@v0.5.0"

      - name: Run Updatecli in enforce mode
        run: "updatecli compose apply --file updatecli-compose.yaml"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
